### ISSUE TITLE
Brainstorming

### ISSUE THREAD

**Issue by MSghais** [AbdelStark/askeladd#3]
@AbdelStark  
I have a few questions/thoughts about the different features and possibilities of the Global Proving System:

Marketplace/Matching engine between Users, Prover provider: 

Questions:
a. Provider/Business can deploy their program into: 
- Backend endpoint, like the Bonsai API (NIP-94 and NIP-96)
- Compiled program deployed with NIP-94/96 or somewhere else: how can we serve it generically and call it in our matching engine or create a load and call program? 
- Maybe another way to deploy it?

In Askeladd, we can implement enum attributes to identify the way developers launch their programs:
Can be a URI for the backend post endpoint with the params required, or a program compiled and deployed on Nostr/Ipfs with the params required.

b. NIP-89: 
If I understand it well, it's mainly used to send applications that can handle a specific kind of event. 
We can create an Event kind of DVM (NIP-90) to verify and prove the Event.

To send Application information:
maybe we can also use the NIP-78/NIP-94/NIP-96 to send application info and metadata (URI, endpoint, download_url, params of request, payment config)

TODO and WIP:

1. Business

a. Send NIP-89 (maybe others) event for Application handler: (content + tags)
- Program reachability: Backend, Compiled program uploaded, other way...
- Create their request_id to be reachable by anyone.
- Parameters of the request_json to prove/verify
- Program reachability: 
It can be served as a backend, or uploaded as a binary with NIP-94 and loaded and called by a Matching engine or SDK.
- Payment config: Amount of Zap for Bitcoin or Tip of Joyboy/AFK for Starknet. 
Difference between the Verify/Proof function of the program.

b. Subscription to request_id of the prover
- Check if the user wants a prove/verify
- Do a matching engine for the payment to occur if needed
- Send a job result with the StarkProof and data 

2. User

User can: 

- Send a request to a specific request_id, with the request_json as job_request. Use a specific event kind of the DVM maybe to differentiate proving/verifying.
- Select between the Proof and Verify functions of a specific program.
- Pay if needed 
- Get the result after paying in ZAP or Tip Starknet Nostr (not required, depends on config of the program provider)

**Comment by AbdelStark** [comment]
Thanks for sharing those ideas. Will have a look and get back to you.

**Comment by AbdelStark** [comment]
Closing, please move in `Discussions`
